version: '3.8'

services:
  app:
    build: .
    container_name: aquilacms_app
    ports:
      - "3010:3010"
    environment:
      - NODE_ENV=production
      - MONGO_URL=mongodb://mongo:27017/aquilacms
    depends_on:
      - mongo
    volumes:
      - .:/src
    command: npm start

  mongo:
    image: mongo:latest
    container_name: aquilacms_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:


